config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  attr_reader :user

  before_action :find_user, only: %i(create edit update)
  before_action :validate_password_reset, only: %i(edit update)

  def new; end

  def create
    user.create_reset_digest
    UserMailer.password_reset(user).deliver_now
    redirect_with_flash :info, t("message.type.info.passwd_reset_sent"), root_url
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      user.errors.add :password, t("error_explanation.empty")
    elsif user.update_attributes user_params
      log_in user
      return redirect_with_flash :success, t("message.type.success.password_reset"), user
    end
    render :edit
  end

  private

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def find_user
    @user = User.find_by email: params[:email].downcase

    return if user

    flash.now[:danger] = t "message.type.danger.email_not_found"
    render :new
  end

  def validate_password_reset
    redirect_to root_url unless user && user.activated? &&
                                user.authenticate?(:reset, params[:id])

    return unless user.password_reset_expired?

    redirect_with_flash :danger, t("message.type.danger.expired_reset_link"),
      new_password_reset_url
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".header" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, t(".password") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t(".password_cf") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".header" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email %>
      <%= email_field_tag :email, class: "form-control" %>

      <%= f.submit t(".submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>