config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.{1}[a-z]+\z/i
  enum sex: %w(male female).freeze
  enum status: {activated: "activated", unactive: "unactive"}

  attr_reader :remember_token, :activation_token, :reset_token

  has_many :microposts, dependent: :destroy
  has_many :active_relationships, inverse_of: :follower,
    class_name: Relationship.name, foreign_key: :follower_id,
    dependent: :destroy
  has_many :passive_relationships, inverse_of: :followed,
    class_name: Relationship.name, foreign_key: :followed_id,
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  validates :name, presence: true,
    length: {maximum: Settings.users.name.length.maximum}
  validates :email, presence: true,
    length: {maximum: Settings.users.email.length.maximum},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, allow_blank: true,
    length: {minimum: Settings.users.password.length.minimum}
  validates :age, presence: true, numericality: {
    only_integer: true, greater_than: Settings.users.age.lwr_bound
  }
  validates :gender, inclusion: {in: sexes.values}

  before_save :downcase_email
  before_create :create_activation_digest

  has_secure_password

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticate? attribute, token
    digest = send "#{attribute}_digest"
    return false unless digest
    BCrypt::Password.new(digest).is_password? token
  end

  def activate
    activated!
    update_attributes activated_at: Time.zone.now
  end

  def current_user? user
    self == user
  end

  def create_reset_digest
    @reset_token = User.new_token
    update_attributes reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    Micropost.feed_of(self).in_desc_time_order
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    @activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_reader :user

  before_action :load_gender_options, only: %i(new create edit update)
  before_action :logged_in_user, only: %i(index edit update destroy)
  before_action :find_user, only: %i(show edit update destroy)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  def index
    @users = User.activated.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def show
    if user.activated?
      @microposts = user.microposts.paginate page: params[:page]
    else
      redirect_with_flash :danger, t("message.type.danger.user_not_active"), root_url
    end
  end

  def create
    @user = User.new user_params
    if user.save
      UserMailer.account_activation(user).deliver_now
      redirect_with_flash :info, t("message.type.info.activate_by_email"), root_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if user.update_attributes user_params
      redirect_with_flash :success, t("message.type.success.update_prof"), user
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    redirect_with_flash :success, t("message.type.success.delete_user"), users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation,
      :age, :gender
  end

  def load_gender_options
    @gender_options = User.sexes.map do |key, value|
      [I18n.t("users.sex.#{key}"), value]
    end
  end

  def logged_in_user
    return if logged_in?

    store_location
    redirect_with_flash :danger, t("message.type.danger.login_first"), login_url
  end

  def correct_user
    redirect_to root_url unless user.current_user? current_user
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]

    return if user

    redirect_with_flash :warning, t("message.type.warning.user_not_found"), root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
  attr_reader :user

  def gravatar_for usr, option = {size: 80}
    @user = usr
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = option[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/users/_follow.html.erb
<%= form_for build_active_relationship, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless user.current_user? current_user %>
  <div id="follow_form">
    <% if current_user.following? user %>
      <%= render "unfollow", user: user %>
    <% else %>
      <%= render "follow", user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for user, url: yield(:url) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t(".label_name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t(".label_email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :gender, t(".label_gender") %>
  <%= f.select :gender, options_for_select(gender_options) %>

  <%= f.label :age, t(".label_age") %>
  <%= f.number_field :age, class: "form-control" %>

  <%= f.label :password, t(".label_passwd") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t(".label_passwd_cf") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_show_follow.html.erb
<% provide :title, title %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for user %>
      <h1><%= user.name %></h1>
      <span><%= link_to t(".view_profile"), user %></span>
      <span><b><%= t ".microposts" %></b> <%= user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if users.any? %>
        <div class="user-avatars">
          <% users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= title %></h3>
    <% if users.any? %>
      <ul class="users follow">
        <%= render partial: "users/user", collection: users %>
      </ul>
      <%= will_paginate users%>
    <% end %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for find_active_relationship(user.id),
  html: {method: :delete}, remote: true do |f| %>
  <%= f.submit t(".submit"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !user.current_user?(current_user) %>
    | <%= link_to t(".delete"), user, method: :delete,
      data: { confirm: t(".confirm") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :url, user_path %>
<% provide :button_text, t(".label_submit") %>
<h1><%= t ".header" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", user: @user, gender_options: @gender_options %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t(".gravatar_change"), "http://gravatar.com/emails",
        target: "_blank", rel: "noopener noreferrer" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".user_index") %>
<h1><%= t ".user_index" %></h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<% provide :url, signup_path %>
<% provide :button_text, t(".label_submit") %>
<h1><%= t ".header1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", user: @user, gender_options: @gender_options %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user-info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "follow_form", user: @user if logged_in? %>
    <%= render "shared/feed", feed_items: @microposts %>
  </div>
</div>