config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, to: "following#index"
        get :followers, to: "followers#index"
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".text1" %>
    <%= link_to t(".link1"), "http://www.railstutorial.org/" %>
    <%= t ".text2" %>
    <%= link_to "Michael Hartl", "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".link2"), about_path %></li>
      <li><%= link_to t(".link3"), contact_path %></li>
      <li><%= link_to t(".link4"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".link1"), root_path, class: "logo" %>
    <div id="nav">
      <%= t "lang.lang" %>:
      <%= link_to_unless_current t("lang.en"), locale: :en %> |
      <%= link_to_unless_current t("lang.vi"), locale: :vi %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".link2"), root_path %></li>
        <li><%= link_to t(".link3"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <%= link_to("#", class: "dropdown-toggle", data: {toggle: "dropdown"}) do %>
              <%= t(".account") %>
              <%= content_tag :b, "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"> </li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".link4"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= prefix_title %>
      <%= t "base_title" %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media:"all",
      "data-turbolinks-track":"reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track":"reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>